name: CI Pipeline

on:
    push:
    pull_request:

jobs:
    run-tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version:
                    - "3.12"
        name: Test
        runs-on: ${{ matrix.os }}
        env:
            SUPABASE_URL: ${{secrets.SUPABASE_URL}}
            SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              working-directory: ./backend
              run: |
                  python -m pip install coverage
                  python -m pip install pytest
                  python -m pip install -r requirements.txt

            - name: Run tests

              run: |
                  coverage run -m pytest --cov --cov-report=xml

            - name: Upload results to Codecov
              uses: codecov/codecov-action@v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
