# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD

on:
    push:
        branches: ["dev"]
        paths:
            - app/**
            - requirements.txt
            - zappa_settings.json

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.12
              uses: actions/setup-python@v3
              with:
                  python-version: "3.12"
            - name: Set up the virtual environment and install dependencies
              run: |
                  python -m venv env
                  source env/bin/activate
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Deploy to AWS with Zappa
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                  # Install the CLI
                  pip install awscli

                  # Configure the CLI
                  aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
                  aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY

                  # Activate the virtual environment
                  source env/bin/activate

                  # Change "dev" to your Zappa environment
                  zappa update dev

        #- name: Test with pytest
        #  run: |
        #    pytest
